import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "selector",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/layouts/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/providers/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/stories/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "login-card-title": "#121212",
        "login-card-subtitle": "#9C9FA8",
        "border-error": "#FDA29B",
        "ring-error-shadow-xs": "#F044383D",
        "text-disabled": "#667085",
        "primary-900": "#101828",
        "primary-dark-900": "#F5F5F6",
        "border-primary": "#D0D5DD",
        "brand-500": "#FF4F18",
        "brand-600": "#F02E06",
        "text-secondary": "#344051",
        "secondary-light": "#F9F9F9",
        "secondary-dark": "#161B26",
        "secondary-700": "#CECFD2",
        disabled: "#F9FAFB",
        "active-dark": "#1F242F",
        "border-secondary": "#EAECF0",
        "bg-disabled": "#F2F4F7",
        "fg-disabled": "#98A2B3",
        "tertiary-600": "#475467",
        "tertiary-dark-600": "#94969C",
        "bg-primary-dark": "#0C111D",
        "border-dark-primary": "#333741",
        "border-brand": "#FFA170",
        "button-secondary-fg": "#344054",
        "error-primary": "#D92D20",
        "fg-success-primary": "#079455",
        "secondary-hover": "#ECECED",
        "brand-dark-noisy": "#FF4F180D",
        "blue-dark-500": "#2970FF",
        "utility-brand-700": "#C71E07",
        "utility-brand-200": "#FFC8A8",
        "utility-brand-50": "#FFF4ED",
        "utility-orange-50": "#511C10",
        "utility-orange-200": "#932F19",
        "utility-orange-700": "#F7B27A",
        "avatar-contrast-border": "#00000014",
        "bg-overlay": "#0C111D",
        "rounded-lines": "#E4E7EC",
        "bg-error-primary": "#FEF3F2",
        "bg-error-dark-primary": "#F044381A",
        "button-primary-error-bg": "#D92D20",
        "button-primary-error-bg_hover": "#B42318",
        "fg-quinary": "#85888E",
        ring: "#2970FFB2",
      },
      boxShadow: {
        input: "0px 2px 2px 0px #E2E2EC33",
        xs: "0px 1px 2px 0px #1018280D",
        "button-ring": "0px 0px 0px 4px #FF4F183D",
        popup: "0px 4px 6px -2px #10182808, 0px 12px 16px -4px #10182814",
      },
      backgroundImage: {
        "login-light-bg": "url(/icons/login-light-bg.svg)",
        "login-dark-bg": "url(/icons/login-dark-bg.svg)",
        "404-light-bg": "url(/icons/404-light-bg.svg)",
        "404-dark-bg": "url(/icons/404-dark-bg.svg)",
      },
    },
  },
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  plugins: [require("tailwindcss-react-aria-components"), require("tailwindcss-animate")],
};
export default config;
